### ISSUE TITLE
Handle new ECS Task ARN format

### ISSUE THREAD

**Issue by kollektiv** [cep21/ecsrun#2]
https://aws.amazon.com/ecs/faqs/#Transition_to_new_ARN_and_ID_format

![image1 a882e9877ffc2554230b7d99db6f5f590b8138f6](https://user-images.githubusercontent.com/85360/63628438-59f37c00-c5c1-11e9-8231-335e40592b27.png)

The current code expects exactly two parts when splitting on `/`.

I will submit a PR for this soon, or if you get to it 😄

**Comment by cep21** [comment]
Let me know if the PR is what you were thinking

**Comment by cep21** [comment]
Resolved in v1.4.1

**Comment by kollektiv** [comment]
Thanks!
